# Generated by Django 5.1.4 on 2025-01-25 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0004_adminlogin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='adminlogin',
            new_name='adminreg',
        ),
    ]
