# Generated by Django 5.1.4 on 2025-02-20 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0007_destinations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destinations',
            old_name='P_id',
            new_name='p_id',
        ),
    ]
