# Generated by Django 5.1.4 on 2025-02-21 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0008_rename_p_id_destinations_p_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='destinations',
        ),
        migrations.AddField(
            model_name='product',
            name='discountprice',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='duration',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
