# Generated by Django 5.1.4 on 2025-02-21 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0009_delete_destinations_product_discountprice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discountprice',
            new_name='discount',
        ),
    ]
